comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "One"
imports_layout = "HorizontalVertical"
wrap_comments = true
# merge_imports = true
reorder_imports = true
group_imports = "StdExternalCrate"
