[package]
name = "aleph-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
downcast-rs = "1.1.1"
log = "0.4"
winit = "0.30.5"
fern = "0.6.2"
human-panic = "2.0.1"
humantime = "2.1.0"
derive_more = { version = "1.0", features = ["debug", "deref"] }

